### ISSUE TITLE
on the new css file

### ISSUE THREAD

**Issue by SauravKumarMahato** [sasa-0000/First_and_Test-rep#4]
A issue is comming on how to set perfect padding and border.

**Comment by sasa-0000** [comment]
_**well don't worry i will be finding some solution to that.**_

**Comment by SauravKumarMahato** [comment]
o
![git_logo svg](https://user-images.githubusercontent.com/83631265/164156713-c2af1beb-bd02-414e-baef-c28b430118e3.png)
k

**Comment by sasa-0000** [comment]
### Ok nice we will do our best
